on:
  push:
    branches: [ main ]

jobs:
  artifact-work:
    runs-on: ubuntu-latest
    steps:
      - name: Create a work file
        run: |
          mkdir -p work-directory
          echo "First in-class" > work-directory/assignment.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: assignment-file
          path: work-directory/assignment.txt
